### ISSUE TITLE
Raspberry PI 5 support

### ISSUE THREAD

**Issue by miroslav-ondra** [UniPiTechnology/unipi-one-modbus#1]
Autodetect RPi 5 due to changes in gpio mapping to pin headers (gpiochip0 -> gpiochip4). Prepare new configs for DI and AO(pwm chip)

**Comment by miroslav-ondra** [comment]
Solved in unipi-os-configurator-data v 0.44 and unipi-on-modbus v 0.20.6

**Comment by rudyvan** [comment]
DI works, but AO seems not to work, but maybe my 12V input on pin AOV is nok (i took it from the low power 12V board).
i ll test further with a separate power supply

**Comment by rudyvan** [comment]
AO works on an RPi 4, not on RPi 5 unfortunately
